# Generated by Django 5.0 on 2023-12-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MusicId', models.IntegerField()),
                ('MusicName', models.CharField(max_length=50)),
                ('ProposedBy', models.CharField(max_length=50)),
                ('DateAdded', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('MusicFile', models.FileField(upload_to='')),
            ],
        ),
    ]
